# Copyright (C) 2026 meta-magic_mount-rs developers
# SPDX-License-Identifier: GPL-v3

[header]
text = "Copyright (C) {{props.inception_year}} {{props.copyright_owner}}\nSPDX-License-Identifier: GPL-v3"

[files]
root = "{{ config_dir }}"
excludes = [
  ".github/bot/requirements.txt",
  ".hintrc",
  "**/*.md",
  "**/*.svg",
  "**/.gitignore",
  "**/*.lock",
  "update/**",
  ".github/renovate.json",
  "module/launcher.png",
  "LICENSE",
  "webui/*.json",
  "webui/src/locales/*.json",
]

[props]
inception_year = 2026
copyright_owner = "meta-magic_mount-rs developers"
